### ISSUE TITLE
github actions runner

### ISSUE THREAD

**Issue by khufkens** [Hyuto/yolov8-onnxruntime-web#3]
Hi there,

Thanks for the code. I've used the small webpage as a demo page for a custom model.

I don't like the javascript ecosystem much (with npm prone to malware etc). I therefore created the below runner so deployment is done automatically to `gh-pages`. Which is fast enough for small iterative changes to the page (mostly changing a title and the model weights).

If using this setup you will also have to change the `package.json` homepage parameter, and see to it that other model parameters match. In my case I use a larger model extent 1920x1920 px.

I'm not doing a pull request, as the changes are minor - and you might want to consider this approach first.

```
name: Build and Deploy

on:
  push:
    branches: [main, master]

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
```
